// ============================================================
// courses.data.js — 课程数据单一真理源 (Phase 4 增强版)
// 新增 syllabus / instructor / 价格 / 评分 等详情页所需字段
// getCourseById() 供 course-detail.html 按 ?id 检索
// ============================================================

export const courses = [
  {
    id: 'ai-basics',
    title: 'AI 基础入门：从零到一',
    difficulty: 'beginner',
    difficultyLabel: '入门',
    weeks: 8,
    lessons: 24,
    icon: 'book',
    iconColor: '#6B8AFF',
    gradientFrom: 'var(--color-primary-soft)',
    gradientTo: '#E8EEFF',
    summary: '机器学习基本概念、神经网络原理，用通俗语言帮你建立完整的 AI 知识体系。',
    description:
      '从机器学习基本概念到神经网络原理，用通俗易懂的方式帮你建立 AI 知识体系。无需数学基础，人人都能学会。课程涵盖机器学习、深度学习、自然语言处理三大核心领域，配合在线实验环境，边学边练。',
    enrolled: 12800,
    rating: 4.9,
    price: 299,
    originalPrice: 599,
    instructor: {
      name: '陈博士',
      title: '前 Google AI 研究员 · AI学社联合创始人',
      bio: '卡内基梅隆大学机器学习博士，曾参与 Google Brain 团队多项核心研究。在自然语言处理和大规模模型训练领域发表论文 20+ 篇。拥有 5 年 AI 教育经验，擅长把复杂概念讲得通俗易懂。',
      initials: '陈',
    },
    syllabus: [
      { title: '什么是人工智能？', description: '了解 AI 的前世今生，从图灵测试到 ChatGPT，建立对 AI 领域的全局认知。', duration: '3 课时 · 第 1 周' },
      { title: '机器学习核心概念', description: '监督学习、无监督学习、强化学习——用生活化的例子讲清楚三大学习范式。', duration: '3 课时 · 第 2 周' },
      { title: '神经网络入门', description: '从神经元到多层网络，不写一行公式，用动画和可视化理解神经网络的工作原理。', duration: '3 课时 · 第 3 周' },
      { title: '深度学习与训练', description: '梯度下降、反向传播——深度学习的核心算法，用浏览器实验环境亲手训练一个模型。', duration: '3 课时 · 第 4-5 周' },
      { title: '自然语言处理入门', description: '从词向量到 Transformer，理解大语言模型背后的核心技术。', duration: '3 课时 · 第 6 周' },
      { title: 'Prompt Engineering 基础', description: '学会与大模型对话——编写高效 Prompt 的核心技巧和最佳实践。', duration: '3 课时 · 第 7 周' },
      { title: '实战项目：搭建你的第一个 AI 应用', description: '综合所学知识，从零搭建一个 AI 问答助手，完成你的第一个 AI 项目作品。', duration: '3 课时 · 第 8 周' },
    ],
  },
  {
    id: 'prompt-engineering',
    title: 'Prompt Engineering 实战',
    difficulty: 'intermediate',
    difficultyLabel: '进阶',
    weeks: 10,
    lessons: 30,
    icon: 'edit',
    iconColor: '#FF6B9D',
    gradientFrom: 'var(--color-secondary-soft)',
    gradientTo: '#FFE8EE',
    summary: '掌握提示工程的核心技巧，学会如何与大模型高效交互，提升工作和学习效率。',
    description:
      '系统学习 Prompt Engineering 的核心方法论，从 Few-shot 到 Chain-of-Thought，从工具调用到多模态提示。课程以实战为导向，每节课都有动手实验，让你真正掌握与大模型协作的能力。',
    enrolled: 9500,
    rating: 4.8,
    price: 399,
    originalPrice: 799,
    instructor: {
      name: '李老师',
      title: '前 OpenAI 技术布道师 · 提示工程专家',
      bio: '曾在 OpenAI 担任技术布道师，参与 GPT-4 的内部测试与优化。对 Prompt 设计和 LLM 行为有深入研究，开设的提示工程课程已帮助 5000+ 学员提升 AI 交互效率。',
      initials: '李',
    },
    syllabus: [
      { title: 'Prompt 基础原理', description: '理解语言模型如何处理提示，掌握基本 Prompt 结构和设计原则。', duration: '3 课时 · 第 1 周' },
      { title: 'Few-shot 与 Zero-shot 技巧', description: '学会用示例引导模型，掌握零样本和少样本提示的核心方法。', duration: '3 课时 · 第 2 周' },
      { title: 'Chain-of-Thought 推理', description: '让模型"展示思维过程"——CoT 提示技术原理与实战应用。', duration: '3 课时 · 第 3-4 周' },
      { title: '角色扮演与系统提示', description: '通过 System Prompt 定义 AI 角色，构建专业领域的 AI 助手。', duration: '3 课时 · 第 5 周' },
      { title: '工具调用与 Function Calling', description: '让 AI 调用外部 API 和工具，实现真正可用的 AI 应用。', duration: '3 课时 · 第 6-7 周' },
      { title: '多模态 Prompt 设计', description: '图像、音频等多模态内容的提示设计，拓展 AI 交互边界。', duration: '3 课时 · 第 8-9 周' },
      { title: '企业级 Prompt 工程实践', description: '构建 Prompt 模板库、A/B 测试、效果监控——企业落地完整方案。', duration: '3 课时 · 第 10 周' },
    ],
  },
  {
    id: 'model-finetune',
    title: '模型微调与部署',
    difficulty: 'advanced',
    difficultyLabel: '高级',
    weeks: 12,
    lessons: 36,
    icon: 'wrench',
    iconColor: '#E0A030',
    gradientFrom: 'var(--color-warning-soft)',
    gradientTo: '#FFF2E6',
    summary: '学习 LoRA、QLoRA 等微调技术，掌握模型量化、部署和 API 封装的全流程。',
    description:
      '深入模型微调与部署的全流程——从数据处理到模型上线，覆盖 LoRA、QLoRA 等前沿微调技术，以及模型量化、Docker 部署和 API 封装的实际工程经验。需具备 Python 基础和深度学习入门知识。',
    enrolled: 4200,
    rating: 4.9,
    price: 599,
    originalPrice: 1199,
    instructor: {
      name: '张工',
      title: '某头部 AI 公司模型架构师',
      bio: '在头部 AI 公司负责大模型训练与部署，主导过多个百亿参数模型的微调项目。对 LoRA、QLoRA 等高效微调方法有丰富的工程落地经验。',
      initials: '张',
    },
    syllabus: [
      { title: '微调基础与数据准备', description: '理解微调原理，学习高质量训练数据的收集、清洗与标注方法。', duration: '3 课时 · 第 1-2 周' },
      { title: 'LoRA 原理与实践', description: '深入理解 LoRA 低秩适配原理，动手微调你的第一个模型。', duration: '3 课时 · 第 3-4 周' },
      { title: 'QLoRA 与量化微调', description: '在消费级显卡上微调大模型——QLoRA 量化技术全解析。', duration: '3 课时 · 第 5-6 周' },
      { title: '模型评估与调优', description: '建立评估体系，使用 PPL、BLEU 等指标科学衡量微调效果。', duration: '3 课时 · 第 7-8 周' },
      { title: '模型量化与压缩', description: 'GPTQ、AWQ 等量化技术，将模型缩小 4-8 倍同时保持性能。', duration: '3 课时 · 第 9-10 周' },
      { title: '部署与 API 封装', description: 'Docker 容器化部署、vLLM 推理加速、API 网关封装——工业级部署方案。', duration: '3 课时 · 第 11 周' },
      { title: '实战：构建垂直领域模型', description: '综合实战——从数据处理到上线，打造一个垂直领域的定制 AI 模型。', duration: '3 课时 · 第 12 周' },
    ],
  },
  {
    id: 'chatbot-dev',
    title: 'AI 聊天机器人开发',
    difficulty: 'intermediate',
    difficultyLabel: '进阶',
    weeks: 8,
    lessons: 24,
    icon: 'chat',
    iconColor: '#10B981',
    gradientFrom: 'var(--color-success-soft)',
    gradientTo: '#E6FFEE',
    summary: '从零搭建智能客服系统，涵盖对话管理、意图识别、多轮对话等核心技术。',
    description:
      '从零到一构建一个生产级 AI 聊天机器人。涵盖对话状态管理、意图识别、知识库集成、多轮对话等核心技术，最终产出一个可部署的智能客服系统。',
    enrolled: 6800,
    rating: 4.7,
    price: 349,
    originalPrice: 699,
    instructor: {
      name: '王老师',
      title: '对话系统架构师 · 前阿里 NLP 工程师',
      bio: '曾在阿里巴巴负责智能客服对话系统架构设计，日处理对话量超百万。对对话管理、NLU、多轮对话有丰富的工程实践经验。',
      initials: '王',
    },
    syllabus: [
      { title: '对话系统概述', description: '了解对话系统的架构演进，从规则匹配到大模型驱动的对话框架。', duration: '3 课时 · 第 1 周' },
      { title: '意图识别与实体抽取', description: '构建 NLU 模块，实现用户意图分类和关键信息提取。', duration: '3 课时 · 第 2 周' },
      { title: '对话状态管理', description: '设计对话状态机，处理多轮对话中的上下文追踪与状态流转。', duration: '3 课时 · 第 3-4 周' },
      { title: 'RAG 知识库集成', description: '接入向量数据库与知识库，让聊天机器人具备实时知识检索能力。', duration: '3 课时 · 第 5 周' },
      { title: '多轮对话策略', description: '设计澄清、追问、兜底等对话策略，提升用户体验。', duration: '3 课时 · 第 6 周' },
      { title: '前端集成与部署', description: 'Web Widget 集成、微信/钉钉接入、消息队列与负载均衡。', duration: '3 课时 · 第 7 周' },
      { title: '实战：企业智能客服', description: '综合实战——从架构设计到上线部署，完成企业级智能客服系统。', duration: '3 课时 · 第 8 周' },
    ],
  },
  {
    id: 'image-gen',
    title: 'AI 图片生成与应用',
    difficulty: 'beginner',
    difficultyLabel: '入门',
    weeks: 6,
    lessons: 18,
    icon: 'palette',
    iconColor: '#7C3AED',
    gradientFrom: 'var(--color-purple-soft)',
    gradientTo: '#E8E8FF',
    summary: '掌握 Stable Diffusion、Midjourney 等工具，学会 AI 绘图的全流程和商业应用。',
    description:
      '从 AI 绘图原理到商业变现，系统学习 Stable Diffusion、Midjourney 等主流工具。课程覆盖文生图、图生图、ControlNet 精确控制、风格迁移等核心技能，附带商业接单实战指导。',
    enrolled: 15200,
    rating: 4.8,
    price: 249,
    originalPrice: 499,
    instructor: {
      name: '苏老师',
      title: 'AIGC 视觉设计师 · 独立艺术家',
      bio: 'AIGC 领域知名创作者，AI 艺术作品多次入选国际展览。为客户提供 AI 视觉设计服务，年营收超百万。擅长将 AI 绘图技术与商业需求结合。',
      initials: '苏',
    },
    syllabus: [
      { title: 'AI 绘图基础原理', description: '理解扩散模型、潜空间等核心概念，建立 AI 绘图的认知框架。', duration: '3 课时 · 第 1 周' },
      { title: 'Stable Diffusion 入门', description: '安装部署 SD，掌握 WebUI 操作，生成你的第一张 AI 作品。', duration: '3 课时 · 第 2 周' },
      { title: 'Prompt 编写技巧', description: '正向/反向提示词、权重语法、风格关键词——写出专业级绘图 Prompt。', duration: '3 课时 · 第 3 周' },
      { title: 'ControlNet 精确控制', description: '姿态控制、线稿上色、深度图——让 AI 按你的想法生成图片。', duration: '3 课时 · 第 4 周' },
      { title: '模型融合与风格迁移', description: 'LoRA 模型训练、风格融合、IP 角色一致性控制。', duration: '3 课时 · 第 5 周' },
      { title: '商业变现与接单实战', description: '海报设计、产品摄影、电商素材——AI 绘图的商业应用全流程。', duration: '3 课时 · 第 6 周' },
    ],
  },
  {
    id: 'rag-practice',
    title: 'RAG 知识库实战',
    difficulty: 'intermediate',
    difficultyLabel: '进阶',
    weeks: 10,
    lessons: 30,
    icon: 'database',
    iconColor: '#FF6B9D',
    gradientFrom: '#FFF5F0',
    gradientTo: '#FFEEE6',
    summary: '构建企业级 RAG 系统，掌握向量数据库、文档切片、检索优化等工程实践。',
    description:
      '从零搭建企业级 RAG 知识库系统——文档解析、向量化、语义检索、重排序、生成回答，全链路实战。课程以企业真实场景为案例，产出可直接上线的 RAG 应用。',
    enrolled: 5600,
    rating: 4.9,
    price: 449,
    originalPrice: 899,
    instructor: {
      name: '刘博士',
      title: '知识图谱与检索专家 · AI学社技术总监',
      bio: '清华大学计算机博士，研究方向为知识图谱与语义检索。曾主导多个千万级文档的 RAG 系统建设，对向量检索、混合搜索有深入研究和丰富的工程经验。',
      initials: '刘',
    },
    syllabus: [
      { title: 'RAG 架构概述', description: '理解 RAG 的核心架构——检索增强生成的完整流程与设计模式。', duration: '3 课时 · 第 1 周' },
      { title: '文档解析与预处理', description: 'PDF/Word/网页多格式解析、文本清洗、Markdown 标准化处理。', duration: '3 课时 · 第 2 周' },
      { title: '文档切片策略', description: '固定长度、语义分段、递归切片——不同场景的最佳切分策略。', duration: '3 课时 · 第 3-4 周' },
      { title: '向量化与向量数据库', description: 'Embedding 模型选型、Chroma/Milvus/Pinecone 实战对比。', duration: '3 课时 · 第 5-6 周' },
      { title: '检索优化与重排序', description: '混合检索、BM25+Reranker、多路召回——提升检索精度。', duration: '3 课时 · 第 7-8 周' },
      { title: '生成回答与幻觉控制', description: 'Prompt 模板设计、引用溯源、幻觉检测——保证回答质量。', duration: '3 课时 · 第 9 周' },
      { title: '实战：企业知识库搭建', description: '综合实战——从文档导入到智能问答，部署完整的企业 RAG 系统。', duration: '3 课时 · 第 10 周' },
    ],
  },
];

export function getCourseById(id) {
  if (!id) return null;
  return courses.find((c) => c.id === id) || null;
}

export default courses;
